# Generated by Django 3.2.5 on 2021-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_index', models.IntegerField()),
                ('words', models.CharField(max_length=300)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
